### ISSUE TITLE
Why use `const void* yuv` instead of `const unsigned char* yuv` as type?

### ISSUE THREAD

**Issue by zchrissirhcz** [metarutaiga/xxYUV#2]
https://github.com/metarutaiga/xxYUV/blob/4e47022a19ec203501f6682e0cb7c9b5c6a803f9/yuv2rgb.h#L14

In the benchmark repo, when calling xxYUV functions, `unsigned char*` type is passed as arguments.

Also, in the implementations of xxYUV, type is also casted to `unsigned char*`.

So, what is the purpose that keep `const void*` as function parameter type?

**Comment by zchrissirhcz** [comment]
https://github.com/metarutaiga/xxYUV/blob/4e47022a19ec203501f6682e0cb7c9b5c6a803f9/yuv2rgb.cpp#L757

There is also `char*` type used: `(char*)yuv + sizeY + 1`. But I wonder if I change it to `unsigned char*` and get same result?

**Comment by metarutaiga** [comment]
I kept `void*` because It can be used for `void*` or `char*` or `unsigned char*`.
So when I called yuv2rgb, I don't need to add any cast.

> https://github.com/metarutaiga/xxYUV/blob/4e47022a19ec203501f6682e0cb7c9b5c6a803f9/yuv2rgb.cpp#L757
> 
> There is also `char*` type used: `(char*)yuv + sizeY + 1`. But I wonder if I change it to `unsigned char*` and get same result?

Here is just an offset operation. `char*` and `unsigned char*` is the same.

**Comment by zchrissirhcz** [comment]
Thanks for explanation. Now I got the idea.
